<?php
   
    $errors = "";
    if ( $http_post ) {
			$errors = retrieve_password();

			if ( ! is_wp_error( $errors ) ) {
				$redirect_to = ! empty( $_REQUEST['redirect_to'] ) ? $_REQUEST['redirect_to'] : 'wp-login.php?checkemail=confirm';
				wp_safe_redirect( $redirect_to );
				exit;
			}
		}

		if ( isset( $_GET['error'] ) ) {
			if ( 'invalidkey' === $_GET['error'] ) {
				$errors->add( 'invalidkey', __( '<strong>Error:</strong> Your password reset link appears to be invalid. Please request a new link below.' ) );
			} elseif ( 'expiredkey' === $_GET['error'] ) {
				$errors->add( 'expiredkey', __( '<strong>Error:</strong> Your password reset link has expired. Please request a new link below.' ) );
			}
		}

		$lostpassword_redirect = ! empty( $_REQUEST['redirect_to'] ) ? $_REQUEST['redirect_to'] : '';
		/**
		 * Filters the URL redirected to after submitting the lostpassword/retrievepassword form.
		 *
		 * @since 3.0.0
		 *
		 * @param string $lostpassword_redirect The redirect destination URL.
		 */
		$redirect_to = apply_filters( 'lostpassword_redirect', $lostpassword_redirect );

		/**
		 * Fires before the lost password form.
		 *
		 * @since 1.5.1
		 * @since 5.1.0 Added the `$errors` parameter.
		 *
		 * @param WP_Error $errors A `WP_Error` object containing any errors generated by using invalid
		 *                         credentials. Note that the error object may not contain any errors.
		 */
		
		?>
            
            <div class="auth creataccount">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-5 col-md-6">
                  <div class="box-auth"><span class="bd bd-top"></span><span class="bd bd-right"></span><span class="bd bd-bottom"></span><span class="bd bd-left"></span><span class="aksen aksen-tl"></span><span class="aksen aksen-tr"></span><span class="aksen aksen-bl"></span><span class="aksen aksen-br"></span>
                    <h1 class="logo-auth"><?php echo file_get_contents( plugin_dir_url(__FILE__) . 'assets/logo-hayform.svg' ); ?></h1>
                    <div class="desc">
                      <h3>Forget password</h3>
                      <p>Please enter your email address. You will receive an email message with instruction on how to reset your password.</p>
                    </div>
                    <form name="lostpasswordform" id="lostpasswordform" action="<?php echo esc_url( network_site_url( 'wp-login.php?action=lostpassword', 'login_post' ) ); ?>" method="post">
                      <div class="form-group">
                        <label>Email address </label>
                        <input class="form-control" name="user_login" id="user_login" type="text" value="<?php echo esc_attr( $user_login ); ?>" placeholder="Enter email address here" autocapitalize="off" autocomplete="username" required="required" />
                      </div>
                        
                        <?php

			/**
			 * Fires inside the lostpassword form tags, before the hidden fields.
			 *
			 * @since 2.1.0
			 */
			do_action( 'lostpassword_form' );

			?>
			<input type="hidden" name="redirect_to" value="<?php echo esc_attr( $redirect_to ); ?>" />
                
                      <div class="form-action">
                        <button class="btn btn-primary btn-small btn-block" name="wp-submit" id="wp-submit" type="submit">Request password reset</button>
                      </div>
                    </form>
                  </div>
                  <div class="have-others text-center">
                    <p>Back to <a href="<?php echo get_home_url();?>/dashboard/">Login</a></p>
                  </div>
                </div>
              </div>
              <footer class="footer">
                <div class="footer-copyright text-center">
                  <p>© 2024 HayForm. All Rights Reserved.</p>
                </div>
              </footer>
            </div>
          </div>